### ISSUE TITLE
Unable to see Slack Webhook option under notification

### ISSUE THREAD

**Issue by babvin** [bitplaces/rundeck-slack-plugin#9]
Hi,
I've placed the jar file /var/lib/rundeck/libext/ 
However, I don't see the option 'Slack web hook' under Notification. Request your help with this regard.

Is there any Step by Step install guide..

**Comment by rhughes1** [comment]
You may have to restart your instance in order for this to work...

**Comment by babvin** [comment]
Thanks, Ryan. I did that and works like a charm...
